#!/usr/bin/env ruby
# Yeah, I know, I should use Clojure.

Dir.chdir "test"
jars=Dir.glob('../lib/*')+Dir.glob('../lib/dev/*')
classpath=jars.join(':')
clojure = %q{(ns semi-sweet-simple.core-test)(run-tests)}
command="java -cp #{classpath} clojure.main -i semi_sweet_simple/core_test.clj -e '#{clojure}'"
Dir.chdir ".."

File.open("run", "w") do | io | 
  io.puts "cd test"
  io.puts command
end

File.chmod(0777, "run")
